### ISSUE TITLE
feature request: Module CSS

### ISSUE THREAD

**Issue by FDiskas** [pucelle/vscode-css-navigation#11]
Hi, thanks again for this cool extention.
Currently I used typescript and `module css` It looks like this
https://github.com/FDiskas/autolist/blob/916b3fcd87b424775725a23cf41df0adcdf6691c/src/client/components/button/ButtonComponent.tsx#L14

So if I click on {styles.~~**button**~~} it jums to definition but not to the source code.
Not sure if it's possible to skip definition and go to source instead.

Can you investigate this?

**Comment by pucelle** [comment]
Yes, it's possible to support `module CSS`, I will work on this next week.

**Comment by FDiskas** [comment]
When it will be released?
Currently using https://marketplace.visualstudio.com/items?itemName=clinyong.vscode-css-modules

**Comment by pucelle** [comment]
Hi, FDiskas, currently I'm still not sure about two questions:
1. Should it support import syntax like `import style as styleHere from '...';`?
2. Currently the auto complete at `style.[CURSOR HERE]` is not limited by the import of the style, but use all the auto complete class names in current work space folder. Is that OK? or it should also be limited?

Thanks.

**Comment by pucelle** [comment]
Otherwise, Thanks for you `vscode-css-modules` the provided, it's useful.

I saw there is a `camelCase` config, which let you can use `style.className` to reference the CSS definition `.class-name` in CSS files. Should we support this?

**Comment by FDiskas** [comment]
basically module css works like so:
If you import with syntax like `import whateverName from './myStyle.css';` Then that means this is module css. Under the hood it will be exported as object not as css. So the autocompleaton should be only from that file.
About camelCase:
```css
.myButton {
   color: red;
}```
will be used in react like so
```jsx
import styles from './myButton.css';
//...
return <button className={styles.myButton} />
```
and if I use not camelCased class names in css file it will be result as the following
```css
.my-button {
  color: red;
}```
```jsx
import styles from './myButton.css';
// ...
return <button className={styles['my-button']} />
```
So everybody is trying to use class names with camelcase
