### ISSUE TITLE
Is this the same of ecmel.vscode-html-css extension or should be used togheter?

### ISSUE THREAD

**Issue by gremo** [pucelle/vscode-css-navigation#35]
Hi, I come into your extension following some GitHub issues/link.

I'm wondering in this extension should be used togheter with https://github.com/ecmel/vscode-html-css or is meant as a substitution. Thanks

**Comment by pucelle** [comment]
I didn't try this plugin, I think some functions should be same with my plugin, and you may meet some conflicts, like repeating results, but should no fatal mistakes.

My plugin having a customized core for parsing CSS files, so you may find it takes only few memory and much faster in searching, But normally you will not notice...

Never mind to give some suggestions if you find.

**Comment by gremo** [comment]
Thanks for helping. I'm just trying to understand how to setup things and get the job done! 

Anyways, do you support heavly-mixin based SCSS files? Like this:

```scss
@each $breakpoint in map-keys($grid-breakpoints) {
  $infix: breakpoint-infix($breakpoint, $grid-breakpoints);

  .breaks#{$infix}-hide {
    @include media-breakpoint-up($breakpoint) {
      br { display: none; }
    }
  }
}
```

I'm wondering if the` .breaks-md-hide` will be detected/suggested?
