### ISSUE TITLE
Autocomplete and Go-to-Definition fail when there is a string interpolation symbol (#)

### ISSUE THREAD

**Issue by NoelAbrahams** [pucelle/vscode-css-navigation#93]
I have the following HTML

```html
<div class="dpe-online__host-panel"></div>
```

When the .scss is like this everything works fine:

```scss
.dpe-online {
    &__host-panel {
    }
}
````

However, both the autocomplete and go-to-def (from the HTML) fail when there is a hash (`#`):

```scss
.dpe-online {
    #{$infoHoverCard-window} {
        position: fixed;
        top: 75px;
        left: calc(50vw - (350px / 2));
    }

    // &__ autocomplete fails

    &__host-panel {
    }
}

```
